### ISSUE TITLE
Interference with webpacker and DevServerProxy

### ISSUE THREAD

**Issue by surzycki** [surzycki/counterfeit#7]
Because FakeSetup and Counterfeit uses Webmock, it triggers errors while running with Webpack-dev-server. This is example change to apply - with that change Webpack-dev-server works fine.
A clever solution is welcome 😄

Right now with that change we can start a dev server in this way:

connect to dev container with picobox ssh dev from two separate terminal windows
in first windows you start rails s
in second you start dev-server with bin/webpack-dev-server
And it should work fine. Link to V2 (handled by webpack-dev-server):
http://localhost:3000/v2/

Without those changes, you should encounter an error described in this issue - > rails/webpacker#822

see also https://github.com/ArizenHQ/coinhouse/pull/42#issuecomment-362624544

**Comment by sepehr500** [comment]
I have this same problem.

**Comment by surzycki** [comment]
Fixed in latest verison

**Comment by sepehr500** [comment]
Thanks. Can you point me to the PR that fixed this issue?

**Comment by surzycki** [comment]
No PR but this is the commit that fixed it:

92a77d07a1bba8a3333b05e2fd475c524b714a76
